server:
  port: 9022

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9001/eureka/
  instance:
      ip-address: true
      instance-id: business9022

feign:
  hystrix:
    enabled: true

