server:
  port: 9023

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9001/eureka/,http://127.0.0.1:9003/eureka/,http://127.0.0.1:9004/eureka/
  instance:
      ip-address: true
      instance-id: business9023

feign:
  hystrix:
    enabled: true

